# This resources needs to be deployed manually, or as part of the argoCD bootstap
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tai-argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  source:
    repoURL: https://github.com/mper0003/tai.git
    targetRevision: HEAD
    path: services/<environment>/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
