apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: applicationset-dev
commonLabels:
  environment: development
nameSuffix: -dev
resources:
  - ../base
patchesStrategicMerge:
  - patch-applicationset-env.yaml
  - patch-tai-application-env.yaml
